version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: cabral
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: tasks
    volumes:
      - ./data:/var/lib/postgresql/data
